---
title: "Biodiversity Analysis"
author: "Luna Eresta Jaya"
date: "`r format(Sys.time(), '%B %d, %Y')`"
# output: html_document
      # toc: true
      # toc_depth: 2
output:
    html_document:
      toc: true
      toc_depth: 2
      toc_float: true
      theme: united
      highlight: tango
editor_options: 
  chunk_output_type: console
---

# Load packages
```{r}
# install.packages("iNEXT")
# install.packages("ggpubr")

# Efficiently load packages
pacman::p_load(phyloseq, iNEXT, ggpubr, tidyverse, install = FALSE)

# Load in functions and color preferences
source("code/functions.R")
source("code/colors_and_shapes.R")
```


# Load data
```{r load-data}
# pre-processed physeq
load("data/preprocessed_physeq.RData")
preprocessed_physeq

# raw metadata file
raw_metadata <- read.csv("data/metadata.txt") %>%
  dplyr::rename(names = Sample.Name) %>%
  mutate(names = gsub("-", ".", names))
head(raw_metadata)
# View(raw_metadata)
```

# Run biodiversity analysis!
## Work with the iNEXT package
```{r iNEXT-div-estimation}
# Prepare data for iNEXT
iNEXT_input_df <- 
  preprocessed_physeq %>%
  otu_table() %>%
  data.frame()

# Run iNEXT on the data --> interpolation and extrapolation of hill numbers
# Warning: Takes ~5 mins to run!
# Calculate diversity with iNEXT
set.seed(12)

# iNEXT_data <- iNEXT(iNEXT_input_df, q = c(0,1,2), datatype = "abundance")
# save(iNEXT_data, file = "data/iNEXT_MissionAransas.RData")

load("data/iNEXT_MissionAransas.RData")
# Note that the object is called "iNEXT_data"

typeof(iNEXT_data)
str(iNEXT_data)

# Make workable dataframe
div_iNEXT_df <-
  iNEXT_data$AsyEst %>%
  dplyr::rename(names = Assemblage) # %>%
  # mutate(names = gsub(".", "", names))
  # make_MA2_metadata()

div_iNEXT_df <-
  merge(div_iNEXT_df, raw_metadata, by.x = "names", by.y = "names")

# View(div_iNEXT_df)
```


# Plot diversity in samples
```{r}
# Set colors and plots for manual plotting with iNEXT
background_col_Indian <- "goldenrod1"
background_col_Chinese <- "firebrick3"
background_col_Malay <- "darkorange2"
background_col_Native <- "grey"
shape_Indian <- 15
shape_Chinese <- 16
shape_Malay <- 17
shape_Native <- 18

###
# Prepare data to color the figure for iNEXT
dat <- colnames(iNEXT_input_df) %>%    
  data.frame() 

colnames(dat)[1] <- "names"

sub_metadata <- merge(dat, raw_metadata, by.x = "names", by.y = "names")

# Add the colors and shapes for the plots
dat_iNEXT <- dat %>%    
  left_join(sub_metadata, by = "names") %>%  
  mutate(ETHNICITY_color = ifelse(ETHNICITY == "Indian", background_col_Indian, 
                                 ifelse(ETHNICITY == "Chinese", background_col_Chinese,
                                        ifelse(ETHNICITY == "Malay", background_col_Malay,
                                               background_col_Native)))) %>%
  mutate(ETHNICITY_shape = ifelse(ETHNICITY == "Indian", shape_Indian, 
                                 ifelse(ETHNICITY == "Chinese", shape_Chinese,
                                        ifelse(ETHNICITY == "Malay", shape_Malay,
                                               shape_Native))))
# View(dat_iNEXT)

# Plot the rarefaction/extrapolation curve (type = 1)
rarefaction_fixed_plot <-   
  ggiNEXT(iNEXT_data, type=1, facet.var="Order.q") +   
  facet_wrap(~Order.q, scales="fixed") +  
  scale_color_manual(values = dat_iNEXT$ETHNICITY_color,  guide = FALSE) +  
  scale_fill_manual(values = dat_iNEXT$ETHNICITY_color, guide = FALSE) +  
  scale_shape_manual(values = dat_iNEXT$ETHNICITY_shape, guide = FALSE) +
  # theme(legend.position = "none") +   
  labs(x = "Number of Sequences")
rarefaction_fixed_plot

scaled_rarefaction_fixed_plot <- rarefaction_fixed_plot + xlim(0, 3000)
scaled_rarefaction_fixed_plot

# Save the file! 
ggsave(rarefaction_fixed_plot,        
       filename = "figures/rarefaction_fixed.png",       
       units = "in", height = 3.5, width = 8)

ggsave(scaled_rarefaction_fixed_plot,        
       filename = "figures/rarefaction_fixed_scaled.png",       
       units = "in", height = 3.5, width = 8)

```


### Pull out specific samples and plot it
```{r}
# Explore the iNEXT object
str(iNEXT_data)

# Pull out information on Rarefaction
str(iNEXT_data$iNextEst$size_based)
# str(iNEXT_data[[2]][1])
## two square brackets on the first one un-lists the first list

# Look into the observed diversity values and check them
obs_rich_df <- 
  iNEXT_data$iNextEst$size_based %>%
  # extract the richness from the data
  dplyr::filter(Order.q == 0) %>%
  dplyr::filter(Method == "Observed") %>% # we only want to look at the observed values
  dplyr::rename(names = Assemblage)
obs_rich_df <- merge(obs_rich_df, raw_metadata, by.x = "names", by.y = "names")
View(obs_rich_df)

# Manually plot the rarefactions based on richness
custom_rarefaction_richness <- iNEXT_data$iNextEst$size_based %>%
  # extract the richness from the data
  dplyr::filter(Order.q == 0) %>%
  dplyr::filter(Method == "Rarefaction") %>% # we only want to look at the observed values
  dplyr::rename(names = Assemblage)
custom_rarefaction_richness <- merge(custom_rarefaction_richness, raw_metadata, by.x = "names", by.y = "names")
custom_rarefaction_richness %>%
  ggplot(aes(x = m, y = qD, color = ETHNICITY, group = names)) +
  geom_line() +
  geom_point(data = obs_rich_df, aes(x = m, y = qD, color = ETHNICITY)) +
  facet_grid(.~ETHNICITY) +
  labs(x = "Number of Sequences", y = "Species Richness") +
  xlim(0, 5000)

### Common Taxa
# New df
obs_shannon_df <- 
  iNEXT_data$iNextEst$size_based %>%
  # extract the shannon from the data
  dplyr::filter(Order.q == 1) %>%
  dplyr::filter(Method == "Observed") %>% # we only want to look at the observed values
  dplyr::rename(names = Assemblage)
obs_shannon_df <- merge(obs_shannon_df, raw_metadata, by.x = "names", by.y = "names")
# View(obs_shannon_df)
# Plot
custom_rarefaction_shannon <- iNEXT_data$iNextEst$size_based %>%
  # extract the shannon from the data
  dplyr::filter(Order.q == 1) %>%
  dplyr::filter(Method == "Rarefaction") %>% # we only want to look at the observed values
  dplyr::rename(names = Assemblage)
custom_rarefaction_shannon <- merge(custom_rarefaction_shannon, raw_metadata, by.x = "names", by.y = "names")
custom_rarefaction_shannon %>%
  ggplot(aes(x = m, y = qD, color = ETHNICITY, group = names)) +
  geom_line() +
  geom_point(data = obs_shannon_df, aes(x = m, y = qD, color = ETHNICITY)) +
  facet_grid(.~ETHNICITY) +
  labs(x = "Number of Sequences", y = "Shannon Diversity") +
  xlim(0, 5000)


### Dominant Taxa
# New df
obs_simpson_df <- 
  iNEXT_data$iNextEst$size_based %>%
  # extract the simpson from the data
  dplyr::filter(Order.q == 2) %>%
  dplyr::filter(Method == "Observed") %>% # we only want to look at the observed values
  dplyr::rename(names = Assemblage)
obs_simpson_df <- merge(obs_simpson_df, raw_metadata, by.x = "names", by.y = "names")
# View(obs_simpson_df)
# Plot
custom_rarefaction_simpson <- iNEXT_data$iNextEst$size_based %>%
  # extract the simpson from the data
  dplyr::filter(Order.q == 2) %>%
  dplyr::filter(Method == "Rarefaction") %>% # we only want to look at the observed values
  dplyr::rename(names = Assemblage)
custom_rarefaction_simpson <- merge(custom_rarefaction_simpson, raw_metadata, by.x = "names", by.y = "names")
custom_rarefaction_simpson %>%
  ggplot(aes(x = m, y = qD, color = ETHNICITY, group = names)) +
  geom_line() +
  geom_point(data = obs_simpson_df, aes(x = m, y = qD, color = ETHNICITY)) +
  facet_grid(.~ETHNICITY) +
  labs(x = "Number of Sequences", y = "Simpson Diversity") +
  xlim(0, 5000)

```


# Completeness Curve
```{r}
ggiNEXT(iNEXT_data, type = 2) +
  scale_color_manual(values = dat_iNEXT$ETHNICITY_color, guide = FALSE) + 
  scale_fill_manual(values = dat_iNEXT$ETHNICITY_color, guide = FALSE) +
  # ZOOM IN
  scale_x_continuous(limits = c(0, 5000))

```


# Boxplot of Diversity
```{r boxplot-div}

iNEXT_data$AsyEst %>%
  head()

richness_boxplot <- obs_rich_df %>%
  ggplot(aes(x = ETHNICITY, y = qD, color = ETHNICITY)) +
  geom_jitter(size = 2.5) +
  geom_boxplot(aes(fill = ETHNICITY), alpha = 0.5, outlier.shape = NA) +
  theme(axis.text.x = element_text(angle = 30, vjust = 1, hjust = 1)) +
  xlab("Ethnicity") +
  stat_kruskal_test()

richness_boxplot_nolowreads <- obs_rich_df %>%
  dplyr::filter(m > 500) %>%
  ggplot(aes(x = ETHNICITY, y = qD, color = ETHNICITY)) +
  geom_jitter(size = 2.5) +
  geom_boxplot(aes(fill = ETHNICITY), alpha = 0.5, outlier.shape = NA) +
  theme(axis.text.x = element_text(angle = 30, vjust = 1, hjust = 1)) +
  xlab("Ethnicity") +
  stat_kruskal_test()

# # Kruskal test
# kruskal.test(qD ~ ETHNICITY,
#              data = dplyr::filter(obs_rich_df, m > 500))

shannon_boxplot <- obs_shannon_df %>%
  ggplot(aes(x = ETHNICITY, y = qD, color = ETHNICITY)) +
  geom_jitter(size = 2.5) +
  geom_boxplot(aes(fill = ETHNICITY), alpha = 0.5, outlier.shape = NA) +
  theme(axis.text.x = element_text(angle = 30, vjust = 1, hjust = 1)) +
  xlab("Ethnicity") +
  stat_kruskal_test()

shannon_boxplot_nolowreads <- obs_shannon_df %>%
  dplyr::filter(m > 500) %>%
  ggplot(aes(x = ETHNICITY, y = qD, color = ETHNICITY)) +
  geom_jitter(size = 2.5) +
  geom_boxplot(aes(fill = ETHNICITY), alpha = 0.5, outlier.shape = NA) +
  theme(axis.text.x = element_text(angle = 30, vjust = 1, hjust = 1)) +
  xlab("Ethnicity") +
  stat_kruskal_test()

# Save the fileS! 
ggsave(richness_boxplot,        
       filename = "figures/20230426_richness_boxplot.png",       
       units = "in", height = 3.5, width = 8)
ggsave(richness_boxplot_nolowreads,        
       filename = "figures/20230426_richness_boxplot_nolowreads.png",       
       units = "in", height = 3.5, width = 8)
ggsave(shannon_boxplot,        
       filename = "figures/20230426_shannon_boxplot.png",       
       units = "in", height = 3.5, width = 8)
ggsave(shannon_boxplot_nolowreads,        
       filename = "figures/20230426_shannon_boxplot_nolowreads.png",       
       units = "in", height = 3.5, width = 8)

```


